# Generated by Django 3.0.8 on 2020-07-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot1', models.CharField(max_length=200, null=True)),
                ('slot2', models.CharField(max_length=200, null=True)),
                ('Slot3', models.CharField(max_length=200, null=True)),
                ('slot4', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
