# Generated by Django 3.0.8 on 2020-07-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Slot3',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slot1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slot2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slot4',
        ),
        migrations.AddField(
            model_name='player',
            name='average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='strike_rate',
            field=models.FloatField(null=True),
        ),
    ]
