# Generated by Django 3.0.8 on 2020-07-15 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200715_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slot1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Slot1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='slot2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Slot2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='slot3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Slot3'),
        ),
        migrations.AddField(
            model_name='customer',
            name='slot4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Slot4'),
        ),
    ]
