# Generated by Django 3.0.8 on 2020-07-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200716_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slot1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Slot1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slot2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Slot2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slot3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Slot3'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slot4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Slot4'),
        ),
    ]
